Fix telepresence logic

diff --git a/bin/stage b/bin/stage
--- a/bin/stage
+++ b/bin/stage
@@ -1,4 +1,7 @@
-#!/usr/bin/env bash
+if [ "$0" = "$BASH_SOURCE" ]; then
+    echo "Error: Script must be sourced"
+    exit 1
+fi
 
 case $1 in
     local|stage|prod) ;;
@@ -6,6 +9,6 @@ case $1 in
       exit 1 ;;
 esac
 
-echo "export STAGE="$1"" > current_stage
+echo "export STAGE="$1"" > "$SHANGREN_ROOT"/.current_stage
 
 source "$SHANGREN_ROOT"/setup_stage.sh
